const { sql } = require('../config/db');

const createGoalsTable = async () => {
  await sql`
    CREATE TABLE IF NOT EXISTS goals (
      id          SERIAL PRIMARY KEY,
      user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      title       TEXT NOT NULL,
      description TEXT,
      progress    INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
      status      TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused')),
      ai_plan     TEXT,   -- JSON string: array of steps generated by AI
      created_at  TIMESTAMPTZ DEFAULT NOW()
    )
  `;
};

module.exports = { createGoalsTable };
